apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client-service
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
