apiVersion: v1
kind: Service
metadata:
  labels:
    app: mguser
  name: mguser-service
spec:
  selector:
    app: mguser
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
