apiVersion: apps/v1
kind: Deployment
metadata:
  name: mguser-deployment
  labels:
    app: mguser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mguser
  template:
    metadata:
      labels:
        app: mguser
    spec:
      containers:
      - name: mguser
        image: genuba/mguser:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        resources: {}
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
      restartPolicy: Always
      serviceAccountName: ""
status: {}
