apiVersion: v1
kind: Service
metadata:
  name: pgcore-service
  labels:
    app: pgcore
spec:
  selector:
    app: pgcore
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer


  
