\i 01_auweb/03_FUNCIONES/US_FU_AUTENTICACION.sql
\i 01_auweb/03_FUNCIONES/US_FU_AGREGARUSUARIO.sql
\i 01_auweb/03_FUNCIONES/US_FU_CONSULTAUSUARIOS.sql
\i 01_auweb/03_FUNCIONES/US_FU_CONSULTAUSUARIO.sql
\i 01_auweb/03_FUNCIONES/US_FU_DELETEUSUARIO.sql
\i 01_auweb/03_FUNCIONES/US_FU_UPDATEUSUARIO.sql