/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 28-may.-2020 8:45:19 p. m. 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

--DROP TABLE GD_TSEND;

/* Create Tables */

CREATE TABLE GD_TSEND
(
	SEND_SEND INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	SEND_TIPO VARCHAR(30) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE GD_TSEND ADD CONSTRAINT PK_SEND_SEND
	PRIMARY KEY (SEND_SEND)
;

/* Create Table Comments */

COMMENT ON TABLE GD_TSEND
	IS 'Tabla de tipos de envio'
;