/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 28-may.-2020 8:45:19 p. m. 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

--DROP TABLE GD_TRECEIVER;

/* Create Tables */

CREATE TABLE GD_TRECEIVER
(
	REC_REC INTEGER NULL GENERATED ALWAYS AS IDENTITY,
	REC_NAME VARCHAR(30) NULL,
	REC_ADDRESS VARCHAR(30) NULL,
	"REC_ EMAIL" VARCHAR(30) NULL,
	REC_DESC VARCHAR(500) NULL,
	REC_TELF VARCHAR(30) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE GD_TRECEIVER ADD CONSTRAINT PK_REC_REC
	PRIMARY KEY (REC_REC)
;

/* Create Table Comments */

COMMENT ON TABLE GD_TRECEIVER
	IS 'Tabla para generar nuevos receptores'
;