/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 28-may.-2020 8:45:19 p. m. 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

--DROP TABLE GD_TDOC;

/* Create Tables */

CREATE TABLE GD_TDOC
(
	DOC_DOC INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	DOC_DATE VARCHAR(50) NULL,
	DOC_ASUNTO VARCHAR(30) NULL,
	DOC_USER VARCHAR(30) NULL,
	DOC_SEND VARCHAR(30) NULL,
	DOC_CODE VARCHAR(30) NULL,
	DOC_CONS INTEGER NULL,
	DOC_RUTE VARCHAR(30) NULL,
	DOC_TYPE INTEGER NULL,
	DOC_COD VARCHAR(30)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE GD_TDOC ADD CONSTRAINT PK_DOC_DOC
	PRIMARY KEY (DOC_DOC)
;

CREATE INDEX IXFK_GD_TDOC_GD_TTYPE ON GD_TDOC (DOC_TYPE ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE GD_TDOC ADD CONSTRAINT FK_GD_TDOC_GD_TTYPE
	FOREIGN KEY (DOC_TYPE) REFERENCES GD_TTYPE (TYPE_TYPE) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments */

COMMENT ON TABLE GD_TDOC
	IS 'Tabla para generar nuevos tipos de documentos'
;