/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 28-may.-2020 8:45:19 p. m. 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

--DROP TABLE GD_TTYPE;

/* Create Tables */

CREATE TABLE GD_TTYPE
(
	TYPE_TYPE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	TYPE_CLASS VARCHAR(30) NULL,
	TYPE_NAME VARCHAR(30) NULL,
	TYPE_CODE VARCHAR(30) NULL,
	TYPE_RUTE VARCHAR(150) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE GD_TTYPE ADD CONSTRAINT PK_TYPE_TYPE
	PRIMARY KEY (TYPE_TYPE)
;

/* Create Table Comments */

COMMENT ON TABLE GD_TTYPE
	IS 'Tabla para generar nuevos tipos de documentos'
;