/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Jun-2020 2:02:40 PM 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE MS_TPERSE
(
	PERSE_PERSE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	PERSE_NAME CHARACTER varying(50) NULL,
	PERSE_ICON CHARACTER varying(200) NULL,
	PERSE_SERV INTEGER NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE MS_TPERSE ADD CONSTRAINT PK_MS_TPERSE
	PRIMARY KEY (PERSE_PERSE)
;

CREATE INDEX IXFK_MS_TPERSE_MS_TSERV ON MS_TPERSE (PERSE_SERV ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE MS_TPERSE ADD CONSTRAINT FK_MS_TPERSE_MS_TSERV
	FOREIGN KEY (PERSE_SERV) REFERENCES MS_TSERV (SERV_SERV) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments */

COMMENT ON TABLE MS_TPERSE
	IS 'Permisos de ejecucion sobre los servicios'
;