/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Jun-2020 2:02:40 PM 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE MS_TRLSV
(
	RLSV_ROL INTEGER NULL,
	RLSV_PERSE INTEGER NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX IXFK_MS_TRLSV_MS_TPERSE ON MS_TRLSV (RLSV_PERSE ASC)
;

CREATE INDEX IXFK_MS_TRLSV_US_TROL ON MS_TRLSV (RLSV_ROL ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE MS_TRLSV ADD CONSTRAINT FK_MS_TRLSV_MS_TPERSE
	FOREIGN KEY (RLSV_PERSE) REFERENCES MS_TPERSE (PERSE_PERSE) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE MS_TRLSV ADD CONSTRAINT FK_MS_TRLSV_US_TROL
	FOREIGN KEY (RLSV_ROL) REFERENCES US_TROL (ROL_ROL) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments */

COMMENT ON TABLE MS_TRLSV
	IS 'Relacion del rol con los permisos sobre la aplicacion'
;