/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Jun-2020 2:02:41 PM 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE US_TROL
(
	ROL_ROL INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	ROL_NOMB CHARACTER varying(100) NULL,
	ROL_DESC CHARACTER varying(200) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE US_TROL ADD CONSTRAINT PK_US_TROL
	PRIMARY KEY (ROL_ROL)
;

/* Create Table Comments */

COMMENT ON TABLE US_TROL
	IS 'Tabla de roles'
;