/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Jun-2020 2:02:41 PM 				*/
/*  DBMS       : DB2 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE US_TUSER
(
	USER_USER INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	USER_ALIAS CHARACTER varying(30) NULL,
	USER_PSWD CHARACTER varying(40) NULL,
	USER_ROL INTEGER NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE US_TUSER ADD CONSTRAINT PK_US_TUSER
	PRIMARY KEY (USER_USER)
;

CREATE INDEX IXFK_US_TUSER_US_TROL ON US_TUSER (USER_ROL ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE US_TUSER ADD CONSTRAINT FK_US_TUSER_US_TROL
	FOREIGN KEY (USER_ROL) REFERENCES US_TROL (ROL_ROL) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments */

COMMENT ON TABLE US_TUSER
	IS 'Tabla que contendra los usuarios del negocio'
;